### ISSUE TITLE
BitcoinJKit - Transactions are lost after restart of the app

### ISSUE THREAD

**Issue by jonasschnelli** [hivewallet/BitcoinKit#1]
Somehow the transactions are not getting stored.
Also theres a missing "transaction list recreation" (load headers till oldest key birthday, then load some proper blocks).
I would also guess that there is a missing <prefix>.blockchain file for non SPV blocks.

**Comment by bazyli** [comment]
I'm not sure I properly understood you. You are saying that allTransactions is not returning you allTransactions after restart?

**Comment by jonasschnelli** [comment]
Yes.
1st run: do a testnet faucet transaction to my given address. Funds arrived. Balance reported (ok).
2nd run: balance is 0 BTC, `allTransactions` response with a empty `NSArray`.

Rmember: i use bitcoinj based BitcoinJKit.

**Comment by bazyli** [comment]
One question. Is the wallet hash changes between those "runs"? It seems that none of the blockchain data (or wallet) is being stored on your machine (you can check the data folder)

**Comment by jonasschnelli** [comment]
The pub key hash stays the same (`[HIBitcoinManager defaultManager].walletAddress`).
In `/Library/Application Support/com.Hive.BitcoinJKit` i have two files:
- bitcoinkit.spvchain
- bitcoinkit.wallet

both files get touched (file last-mod.-date changed) after every run (which probably is okay).

**Comment by jonasschnelli** [comment]
it's because of a missing autosave wallet.

http://code.google.com/p/bitcoinj/source/browse/core/src/main/java/com/google/bitcoin/kits/WalletAppKit.java?r=ee0b56180b1826313a22781fc652101a68ea7f17#94

Will create a pull request soon.

**Comment by jonasschnelli** [comment]
should be fixed with #2. Close

**Comment by hivewallet** [comment]
Is this closed or is it not? @bazyli please confirm
