### ISSUE TITLE
wallet file is overwritten if it's unreadable on startup

### ISSUE THREAD

**Issue by mackuba** [hivewallet/BitcoinKit#11]
There's some code in BitcoinManager class that tries to load the wallet file, and if it can't, then it creates a new wallet file. However, if the reason why the file can't be read is not that it's not there, but that it's just unreadable, the existing wallet file gets overwritten.

To reproduce:
- start Hive, look at the address
- `chmod 000 ~/Library/Application\ Support/Hive/BitcoinJ.network/bitcoinkit.wallet` while Hive is not running
- start Hive again - it will create a new `bitcoinkit.wallet` with permissions `644` and the address will be different

**Comment by jonasschnelli** [comment]
two possible solutions could be implemented:

1) try to mv possible existing wallet to bitcoinkit.wallet_sanity (to prevent losing keys)
2) try to fix permissions and make file readable
2a) ask for Admin/Root privileges to fix / chmod the wallet file

or other solutions?

**Comment by mackuba** [comment]
I'd just say tell the user the wallet is unreadable and don't continue (meaning either crash or stop bitcoinj initialization and show a read-only UI). I think if the wallet file has no read permissions then something went seriously wrong, this shouldn't happen in any normal situation except when you're messing with it yourself. Could be perhaps if your system volume was somehow magically mounted in read-only mode or something like that, but in any case, it's not something that needs to be handled very gracefully - just make sure the wallet stays safe if that happens.

**Comment by jonasschnelli** [comment]
@jsuder make sense. i'll take a look in how it is possible to detect the distinction between "missing wallet" and "unreadable wallet". The error handling on the [kit start] method is also not the best end might be improved for that.
But it is important.

**Comment by hivewallet** [comment]
+1 for the bitcoinkit.wallet_sanity consideration though.

**Comment by nschum** [comment]
We now don't continue if the wallet is unreadable. Additionally we expose the error through an NSError parameter in `start:` so the client can show an appropriate error message. (If NULL is passed for the NSError, an exception will be thrown if the wallet is unreadable instead.)
