### ISSUE TITLE
add a mandatory wallet extension field to break compatibility with other clients

### ISSUE THREAD

**Issue by mackuba** [hivewallet/BitcoinKit#14]
Jim:

> But what if someone uses some old code, or some other bitcoinj based wallet to open it ?
> You can get into a situation (if you are not careful) where another user "almost" opens a wallet.
> Then saves it, but they mess up the private keys write - perhaps they don't understand your encrypted private keys) and don't write them
> BANG - bitcoins lost
> For MultiBit I actually put in a mandatory extension into the wallet - it's only purpose is that if non-multibit code tries to open the wallet if cannot
> you can put in extra data in the Wallet in the extension field
> If you have a look at MultiBitProtobufWalletSerializer (or maybe the protobuf and wallet is the other way round) you'll see what I mean
> in the wallet protobuf you can mark the extension as 'mandatory' which basically means 'if you don't understand this, you have to stop'

**Comment by mackuba** [comment]
And by other clients I mean clients not based on BitcoinKit.

**Comment by mikehearn** [comment]
Have you actually made an incompatible change to the wallet format? It'd be a shame to do this for no actual reason. In future apps like Bitcoin Wallet on Android will start using the bitcoinj wallet format for backups, and so it'd be nice to have some interop there.

By all means, go ahead and do this if you modify the format in some way (this is what Jim did and why he had to fork the format), but please avoid it if possible.

**Comment by mackuba** [comment]
> Have you actually made an incompatible change to the wallet format?

So far we haven't, I just assumed this was a good idea based on the conversation above... We've had reports that Multibit is able to open Hive wallets (https://github.com/hivewallet/hive-osx/issues/117), so wouldn't that mean that you can mess up a wallet this way if Multibit's format is not fully compatible?

**Comment by mikehearn** [comment]
Well, if MultiBit is opening wallets that lack its own mandatory "fork the format" extension that sounds like a bug in MultiBit, but I don't recall exactly what the difference is/was. It wasn't very major. Jim is best placed to answer these questions. But basically it's his job to ensure MultiBit doesn't mess things up if it's given wallets that it can't handle.
