### ISSUE TITLE
edit the pom.xml files to make them independent of bitcoinj

### ISSUE THREAD

**Issue by mackuba** [hivewallet/BitcoinKit#16]
Right now the pom files are poorly written, they're basically edited copies of bitcoinj's ones, and they happen to work but they cause problems during bitcoinj upgrades. I think that our two poms should be merged, and they should include bitcoinj as a proper dependency explicitly listed in the file, not included through a symlinked subdirectory, and then we can remove bitcoinj's dependencies from our poms. (But we need to make sure that the latest checked out version from the submodule is included during the build, not some cached one from the local repo that just happens to have the same version number.)

**Comment by nschum** [comment]
I'm almost ready, but why do we use a submodule at all and not simply the latest [released jar](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google%22%20AND%20a%3A%22bitcoinj%22)?

**Comment by mackuba** [comment]
If I remember correctly, bitcoinj was only added the the maven repo very recently, before 0.11 release (and that's when our setup broke), so it wasn't possible to do it this way before.

One thing I was worried about - I sometimes needed to edit stuff in bitcoinj, to add some temporary debug logs, to debug a problem either in bitcoinj or in bitcoinkit. If I wanted to do this now, I'd have to temporarily edit the maven config too to point to a local copy, right? Something like in Ruby you'd put `:path => ~/Projects/bitcoinj` in the gemfile, if you know what I mean.

**Comment by nschum** [comment]
OK, that's what I thought. I would go for the released version then.

You can still install a modified version into your local .m2 repo to use it (under a different version number or name).

**Comment by mackuba** [comment]
Nice work, it should make it much easier to update and change things now, thanks.

This can be closed, right?
