### ISSUE TITLE
fee calculation

### ISSUE THREAD

**Issue by jonasschnelli** [hivewallet/BitcoinKit#18]
the java method  `feeForSendingCoins` as well as corresponding Obj-C method  `- (uint64_t)calculateTransactionFeeForSendingCoins:(uint64_t)coins` might calculate the wrong fee.

What about implementing the approach of creating a send request (but not committing!), get the fee and keep the request until the user "commits" or "cancel"?
Should be more accurate.

I would say the `REFERENCE_DEFAULT_MIN_TX_FEE` will not be correct in every case.

**Comment by nschum** [comment]
Yes, that is correct. But do we need to keep the request, or isn't the creation of the request deterministic.

On the other hand, we want to make the fee user-definable, so the exact value might not be relevant.

**Comment by jonasschnelli** [comment]
The fee might change after waiting some time and create the same type of request (same amount, etc.). That's why i would recommend to keep the request. I think it's quit trivial to keep it.
User-definable fee is a nice thing but the calculated fee should always be visible (as recommended fee).

**Comment by mackuba** [comment]
Related: https://github.com/hivewallet/hive-osx/issues/196

**Comment by nschum** [comment]
I disagree about it being trivial. That means adding state to a so-far stateless API call. We have to return a handle to the request, make sure the request gets cleaned up, even if we never hear back from the client, figure out how old the pending request is allowed to be ...

I'd rather re-create the request object, compare the calculated fee and optionally report back to the client if it should be changed.

**Comment by jonasschnelli** [comment]
@nschum hmm.. re-creating the request object might end up in a different fee (because between calc-request and send-request can be n time).
I know it add's somehow a "state" which is ugly,.. but effective in that case. The sendRequest object could also be held somehow in the application layer (instead of BitcoinKit) which would make the implementation a bit more complex.

Have a look here (https://github.com/jonasschnelli/BitcoinJKit/blob/master/BitcoinJKit/java/bitcoinkit/src/main/java/com/hive/bitcoinkit/BitcoinManager.java) and follow `pendingSendRequest`.

**Comment by nschum** [comment]
If the calculated fee changes, we can tell the client (if it is interested). The client would only have to pass the expected fee as an argument.

**Comment by mackuba** [comment]
I'd also be against forcing the UI layer to keep a returned request object and reuse it later or something like that, this would complicate things too much. Just changing the fee calculation method so that it builds a real request object and then discards it should work in 99.99% cases, unless a lot of time passes between the fee calculation and the sending of the coins.

**Comment by jonasschnelli** [comment]
agreed.
I try to implement that (because i move MacWallet back to the standard HIBitcoinKit).

**Comment by nschum** [comment]
Sorry, didn't mean to close the issue.

**Comment by mackuba** [comment]
Done.
