### ISSUE TITLE
package name for Java classes should be com.hivewallet, not com.hive

### ISSUE THREAD

**Issue by mackuba** [hivewallet/BitcoinKit#23]

**Comment by ghost** [comment]
Why? The product is called "Hive", not "Hive wallet"

**Comment by mackuba** [comment]
Because in Java the product packages are supposed to be based on your domain name, which in our case is hivewallet.com, not hive.com :p  

## 

Jakub Suder
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
