### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [hivewallet/BitcoinKit#28]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by mackuba** [comment]
Mate, this project hasn't been touched (not to mention properly maintained, which it never really was) in 5.5 years :-) I forgot to mark it as archived, I will now.

**Comment by Neustradamus** [comment]
@mackuba: Ok, badly!
