### ISSUE TITLE
Rename to "bitcoinkit.framework"

### ISSUE THREAD

**Issue by hivewallet** [hivewallet/BitcoinKit#6]
Lowercase project name for consistency

**Comment by jonasschnelli** [comment]
hmm... i would recommend to stick to the OSX quasi-standard which is camel case starting with uppercase.
Also most third party frameworks also starts with uppercase letter (check the famous https://github.com/andymatuschak/Sparkle)

check a partial dir dump of /System/Library/Frameworks
`Accelerate.framework         IOSurface.framework
Accounts.framework          ImageCaptureCore.framework
AddressBook.framework           ImageIO.framework
AppKit.framework            InputMethodKit.framework
AppKitScripting.framework       InstallerPlugins.framework
AppleScriptKit.framework        InstantMessage.framework`

**Comment by hivewallet** [comment]
I only mean the project name on GitHub, but if that's also the trend for GitHub project names, then let's go with that.

**Comment by jonasschnelli** [comment]
A sure. That another story :-)...

**Comment by mackuba** [comment]
I think GitHub project names are also usually capitalized in case of Cocoa frameworks/libs, see https://github.com/search?l=Objective-C&q=framework&source=cc&type=Repositories.
